version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: dolibarr_db
    restart: always
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db:/var/lib/mysql
    environment:
        - MYSQL_DATABASE=dolibarr
        - MYSQL_USER=dolibarr
        - MYSQL_PASSWORD=dolibarr
        - MYSQL_RANDOM_ROOT_PASSWORD=yes

  dolibarr:
    image: upshift/dolibarr:latest
    container_name: dolibarr_webui
    restart: always
    depends_on:
        - mariadb
    ports:
        - 8080:80
    environment:
        - DOLI_DB_HOST=mariadb
        - DOLI_DB_NAME=dolibarr
        - DOLI_DB_USER=dolibarr
        - DOLI_DB_PASSWORD=dolibarr
    volumes:
        - ./html:/var/www/html
        - ./docs:/var/www/documents
