version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: dolibarr_web
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      # - ./config/php.ini:/usr/local/etc/php/php.ini  # optional
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: dolibarr_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=dolibarr
      - MYSQL_PASSWORD=dolibarr
    volumes:
      - ./db:/var/lib/mysql
