# https://github.com/zabbix/zabbix-docker/blob/6.2/docker-compose_v3_alpine_pgsql_latest.yaml

version: "3.8"

services:
  zabbix-database:
    image: timescale/timescaledb:latest-pg14
    container_name: zabbix-timescaledb
    restart: unless-stopped
    env_file:
     - .env
    volumes:
      - timescaledb:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432
    networks:
      - zabbix_net

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.2-latest
    container_name: zabbix-server
    restart: unless-stopped
    ports:
     - "10051:10051"
    env_file:
     - .env
    depends_on:
    - zabbix-timescaledb
    networks:
      - zabbix_net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.2-latest
    container_name: zabbix-web
    restart: unless-stopped
    env_file:
     - .env
    environment:
      ZBX_SERVER_HOST: zabbix-server
    labels:
      traefik.enable: true
      traefik.http.routers.zabbix.entrypoints: https
      traefik.http.routers.zabbix.rule: Host(`monitoring.example.com`)
      traefik.http.routers.zabbix.tls: true
      traefik.http.routers.zabbix.tls.certresolver: lets
    depends_on:
      - zabbix-server
    networks:
      - traefik_proxy
      - zabbix_net

networks:
  traefik_proxy:
    external: true
  zabbix_net:


volumes:
  timescaledb:
