version: "3.8"

services:
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.2-latest
    container_name: zabbix-agent
    restart: unless-stopped
    ports:
     - "10050:10050"
    environment:
      ZBX_HOSTNAME: srv1.example.com
      ZBX_SERVER_HOST: monitoring.example.com
    privileged: true
