---
version: "3.8"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entryPoints=https"
      - "traefik.http.routers.api.rule=Host(`traefik.example.com`)" # Change domain
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=lets"

      - "traefik.http.routers.api.middlewares=api-auth"
      - "traefik.http.middlewares.api-auth.basicauth.users=test:$$2y$$05$$1YvGsH9eUxN9ni00DLWAO.VdGubBQ5IM/4EM6TGPN0wEIVE0C9rXO"  # user: test pass: test
    command:
      - '--api'
      - '--providers.docker=true'
      - '--providers.docker.network=traefik_proxy'
      - '--providers.docker.exposedByDefault=false'
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'
      - '--log=true'
      - '--log.level=DEBUG'
      - '--log.filepath=/var/log/traefik.log'
      - "--certificatesresolvers.lets.acme.httpchallenge=true"
      - "--certificatesresolvers.lets.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.lets.acme.email=CHANGEME@example.com"  # Change domain
      - "--certificatesresolvers.lets.acme.storage=/letsencrypt/acme.json"
    networks:
      - traefik_proxy
    ports:
      - 80:80
      - 443:443
    restart: always

networks:
  traefik_proxy:
    name: traefik_proxy
