# https://hub.docker.com/_/postgres

version: "3.1"

services:
  mariadb:
    image: postgres:13-alpine
    restart: always
    container_name: postgres
    hostname: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: Eyh9!7IgV1NB
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend
    ports:
      - "5432:5432"

networks:
  backend:
    external: true

volumes:
  postgres:
