[app]
address = "0.0.0.0:9000"

[db]
host = "listmonk-db"
port = 5432
user = "root"
password = "listmonk123"
database = "listmonk"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
