---
version: "3.8"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    volumes:
      - ./certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.api.entrypoints: https
      traefik.http.routers.api.rule: Host(`traefik.test`)
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.tls: true
    command:
      - '--api'
      - '--providers.docker=true'
      - '--providers.docker.network=traefik_proxy'
      - '--providers.docker.exposedByDefault=false'

      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'

      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'

      - '--providers.file.filename=/certs/dynamic.yml'
      - '--providers.file.watch=true'

      - '--log.filePath=/dev/stdout'
      - '--log.level=DEBUG'
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik_proxy
    depends_on:
      - dnsmasq

  dnsmasq:
    image: anzevalher/dnsmasq:latest
    restart: unless-stopped
    container_name: dnsmasq
    ports:
      - 53:53/udp
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro

networks:
  traefik_proxy:
    name: traefik_proxy
