---
version: "3.8"

services:
  mariadb:
    image: mariadb:10.3
    restart: unless-stopped
    container_name: mariadb
    hostname: mariadb
    volumes:
      - ./data:/var/lib/mysql
      - $PWD/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=SUPERSECRET
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - mariadb_network


networks:
  mariadb_network:
    name: mariadb_network
