# https://github.com/ChristianLempa/boilerplates/blob/main/docker-compose/prometheus/config/prometheus.yml
# https://github.com/vegasbrianc/prometheus/blob/master/prometheus/prometheus.yml

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # A short evaluation_interval will check alerting rules very often.
  # It can be costly if you run Prometheus with 100+ alerts.
  evaluation_interval: 20s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #   monitor: 'lab-monitor'

rule_files:
  - 'alerts/*.yml'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
    basic_auth:
      username: "test"
      password: "test"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          alias: 'prometheus'
    basic_auth:
      username: "test"
      password: "test"

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    basic_auth:
      username: "test"
      password: "test"

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    basic_auth:
      username: "test"
      password: "test"

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    basic_auth:
      username: "test"
      password: "test"
