---
version: "3.8"

services:
  wikijs:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs
    restart: always
    depends_on:
      - wikijs_postgres
    volumes:
      - ./data:/data
    environment:
      - DB_TYPE=postgres
      - DB_HOST=wikijs_postgres
      - DB_PORT=5432
      - DB_NAME=wikijs
      - DB_USER=wikijs
      - DB_PASS=wikijs
    ports:
      - 3000:3000
    networks:
      - wikijs-network

  wikijs_postgres:
    image: postgres:14-alpine
    container_name: wikijs_postgres
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijs
      POSTGRES_DB: wikijs
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - wikijs-network

networks:
  wikijs-network:
    name: wikijs-network
