# https://hub.docker.com/_/postgres

version: "3.1"

services:
  mariadb:
    image: postgres:13-alpine
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - backend
  
networks:
  backend:
    external: true
            
