---
version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - postgres_network

networks:
  postgres_network:
    name: postgres_network
